### ISSUE TITLE
Command 'nlmp' can lag a server.

### ISSUE THREAD

**Issue by ribagi** [DevotedMC/NameLayer#33]
The command 'nlmp' causes a large amount of lag when moderately spammed.

**Comment by ProgrammerDan** [comment]
Ty, will look into it. Would a simple rate limiter be OK or more complex
lockdown?

**Comment by ribagi** [comment]
A rate limiter can work (Would stop a DOSs), can it be done on a global level? The only thing is a single use of the command does do some lag on the server.

**Comment by ProgrammerDan** [comment]
Yeah, gotcha. Should be doable. You are using latest from this repo or do
you need me to merge in anything from classic fork?

On Jan 26, 2019 19:12, "ribagi" <notifications@github.com> wrote:

A rate limiter can work (Would stop a DOSs), can it be done on a global
level? The only thing is a single use of the command does do some lag on
the server.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/DevotedMC/NameLayer/issues/33#issuecomment-457877480>,
or mute the thread

**Comment by ribagi** [comment]
We are forking off this Devoted's branch, from the commit 92e006b. But I dont think it would matter.

**Comment by ProgrammerDan** [comment]
working on it here: https://github.com/DevotedMC/NameLayer/tree/1.12-feature-ratelimit

haven't tested yet, but basic idea is there.

Not sure exactly how exploited but noticed it was trivially exploitable via both tab complete and actual command issue, so rate limiter applied to both

**Comment by ribagi** [comment]
@ProgrammerDan Thanks dan. It would make sense that the tab complete is doing fun things as the PermissionsById size is over 3 million.

**Comment by ProgrammerDan** [comment]
Might be best to test this out before merging into live server. Let me know if anything comes up during test, I'm working on NL 1.13 tonight but will get back to this either later tonight or tomorrow.
